# Generated by Django 5.1.7 on 2025-03-30 11:01

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('langflow_integration', '0003_chatsession_is_active_and_more'),
        ('sessions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='chatsession',
            name='unique_user_session',
        ),
        migrations.RemoveConstraint(
            model_name='chatsession',
            name='unique_anon_session',
        ),
        migrations.AddConstraint(
            model_name='chatsession',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('user',), name='unique_active_user_session'),
        ),
        migrations.AddConstraint(
            model_name='chatsession',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('session',), name='unique_active_anon_session'),
        ),
    ]
